# Generated by Django 5.0.4 on 2024-04-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
